### ISSUE TITLE
FileNotFoundError: [Errno 2] 01.KEGG_Regular_Module_Information.pickle

### ISSUE THREAD

**Issue by rzhan186** [cruizperez/Microbe_Annotator#17]
Dear MicrobeAnnotator developers, 

I tried to annotate two bins with the light mode using blast as my search method, however, it returned a FIleNotFoundError with “01.KEGG_Regular_Module_Information.pickle” being the missing file. The software was used in a virtual python environment in a cluster instead of using Conda. I thought KEGG is not freely available, is it possible that the error was caused by the fact that I do not a KEGG subscription? 

Could you help with this? Thank you!

Rui 

2021-05-10 02:33:22,505 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ---- 
2021-05-10 02:33:22,505 [INFO]: Validating user inputs
2021-05-10 02:33:22,543 [INFO]: Passed
2021-05-10 02:33:22,544 [INFO]: Processing 2 files. I will run 2 files in parallel with 24 threads per file.
2021-05-10 02:33:22,544 [INFO]: Running in light mode. Searching only KOfam and Swissprot using blast.
2021-05-10 02:33:23,270 [INFO]: Searching proteins against KOfam profiles
2021-05-10 02:33:23,270 [INFO]: Parsing HMM profile metadata
2021-05-10 02:33:38,597 [INFO]: Filtering and saving results...
2021-05-10 02:33:38,697 [INFO]: Search against KOfam done!
2021-05-10 02:34:36,306 [INFO]: Filtering and saving results...
2021-05-10 02:34:36,475 [INFO]: Search against KOfam done!
2021-05-10 02:34:37,122 [INFO]: Searching proteins against Swissprot
2021-05-10 03:28:36,327 [INFO]: Extracting Swissprot annotation data
2021-05-10 03:28:49,720 [INFO]: MicrobeAnnotator annotation has finished succesfully!
2021-05-10 03:28:49,721 [INFO]: Summarizing results
2021-05-10 03:28:49,724 [INFO]: Extracting ko numbers and summarizing results
Importing data... Traceback (most recent call last):
  File "/home/ruizhang/microbe_annotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/ruizhang/microbe_annotator/bin/microbeannotator", line 969, in main
    module_information, metabolism_matrix, module_group_matrix = ko_mapper.module_information_importer(annotation_files)
  File "/home/ruizhang/microbe_annotator/lib/python3.7/site-packages/microbeannotator/pipeline/ko_mapper.py", line 93, in module_information_importer
    regular_modules = import_module_dict(data_folder / "01.KEGG_Regular_Module_Information.pickle")
  File "/home/ruizhang/microbe_annotator/lib/python3.7/site-packages/microbeannotator/pipeline/ko_mapper.py", line 83, in import_module_dict
    pickle_in = open(dictionary_location,"rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruizhang/microbe_annotator/lib/python3.7/site-packages/microbeannotator/data/01.KEGG_Regular_Module_Information.pickle'

**Comment by cruizperez** [comment]
Hi @Rui-Zzhang,
It seems we are having some issues with the associated data when MicrobeAnnotator is installed using pip. Can you confirm this is the case? If so, you could try installing it from Conda and it should work. Let me know if it does not.

**Comment by ashuiit** [comment]
@cruizperez, I have installed microbeannotator on conda but still getting the same error of '01.KEGG_Regular_Module_Information.pickle'. If anyone has solved it please share the debugging technique.

**Comment by Julboteroc** [comment]
Hey, first, thank you for making MicrobeAnnotator.
I had the same problem and I solved by copying and pasting the files that are missing inside the anaconda environment.
`git clone https://github.com/cruizperez/MicrobeAnnotator`
then the missing files are going to be in `/home/user/MicrobeAnnotator/microbeannotator/data/01.KEGG_Regular_Module_Information.pickle`
then you just have to copy and paste the file
`cd /home/cd/microbe_annotator/lib/python3.7/site-packages/microbeannotator/data/`
`cp /home/user/MicrobeAnnotator/microbeannotator/data/01.KEGG_Regular_Module_Information.pickle .`
