### ISSUE TITLE
2.0.5 error. I use our own database on PACE

### ISSUE THREAD

**Issue by jianshu93** [cruizperez/Microbe_Annotator#36]
microbeannotator -i MetaBAT.005.faa -o MetaBAT_annotator -t 12 -p 1 -d /storage/home/hcoda1/4/jzhao399/p-ktk3-0/shared3/shared3/DB/MicrobeAnnotator_New -m diamond 

2021-08-25 20:50:54,822 [INFO]:  ---- This is MicrobeAnnotator v2.0.5 ---- 
2021-08-25 20:50:54,822 [INFO]: Validating user inputs
2021-08-25 20:50:54,824 [INFO]: Passed
2021-08-25 20:50:54,824 [INFO]: Processing 1 files. I will run 1 files in parallel with 12 threads per file.
2021-08-25 20:50:54,981 [INFO]: Searching proteins against KOfam profiles
2021-08-25 20:50:54,981 [INFO]: Parsing HMM profile metadata

2021-08-25 20:58:32,717 [INFO]: Filtering and saving results...
2021-08-25 20:58:32,723 [INFO]: Search against KOfam done!
2021-08-25 20:58:33,837 [INFO]: Searching proteins against Swissprot
2021-08-25 20:58:40,756 [INFO]: Extracting Swissprot annotation data
2021-08-25 20:58:40,768 [INFO]: Searching proteins against RefSeq
2021-08-25 21:53:07,983 [INFO]: Extracting RefSeq annotation data
2021-08-25 21:53:07,989 [INFO]:Searching proteins against Trembl
Error: Error detecting input file format. First line seems to be blank.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 232, in similarity_search
    blast_filter_slow(method_output_file, filtered_file, id_perc, bitscore, evalue, aln_percent)
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 138, in blast_filter_slow
    with open(input_tab) as blast_input:
FileNotFoundError: [Errno 2] No such file or directory: 'MetaBAT_annotator/trembl_results/MetaBAT.005.faa.step_4.diamond'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/bin/microbeannotator", line 755, in main
    multiple_arguments=arguments_to_pass), input_proteins)
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'MetaBAT_annotator/trembl_results/MetaBAT.005.faa.step_4.diamond'

Any idea how to fix?

With old version and old database I am ok but the old database now is not here.

Thanks,

Jianshu

**Comment by rotheconrad** [comment]
Jianshu did you figure this out? It looks like as you say it can't find the database file it is looking for. You need to rebuild the database. I have two working versions of MicrobeAnnotator (v1 and v2) I can give you the file path to use if you need it. Let me know.

**Comment by jianshu93** [comment]
yes. old database you shared works
